// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VideogameArchiveAPI.Data;

#nullable disable

namespace VideogameArchiveAPI.Migrations
{
    [DbContext(typeof(VideogameArchiveAPIDbContext))]
    [Migration("20251212112200_FixVideoGameDLCs")]
    partial class FixVideoGameDLCs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("CompanySequence");

            modelBuilder.Entity("CustomFolderVideogameUser", b =>
                {
                    b.Property<int>("CustomFoldersFolderId")
                        .HasColumnType("integer");

                    b.Property<int>("VideogamesUserVideogameUserId")
                        .HasColumnType("integer");

                    b.HasKey("CustomFoldersFolderId", "VideogamesUserVideogameUserId");

                    b.HasIndex("VideogamesUserVideogameUserId");

                    b.ToTable("CustomFolderVideogameUser", (string)null);
                });

            modelBuilder.Entity("DeveloperVideogame", b =>
                {
                    b.Property<int>("DevelopersCompanyId")
                        .HasColumnType("integer");

                    b.Property<int>("GameListGameId")
                        .HasColumnType("integer");

                    b.HasKey("DevelopersCompanyId", "GameListGameId");

                    b.HasIndex("GameListGameId");

                    b.ToTable("VideogamesDevelopers", (string)null);
                });

            modelBuilder.Entity("GameModeVideogame", b =>
                {
                    b.Property<int>("GameModesGameModeId")
                        .HasColumnType("integer");

                    b.Property<int>("VideogameListGameId")
                        .HasColumnType("integer");

                    b.HasKey("GameModesGameModeId", "VideogameListGameId");

                    b.HasIndex("VideogameListGameId");

                    b.ToTable("VideogamesGameModes", (string)null);
                });

            modelBuilder.Entity("GamingPlatformVideogame", b =>
                {
                    b.Property<int>("GamingPlatformsConsoleId")
                        .HasColumnType("integer");

                    b.Property<int>("VideogameListGameId")
                        .HasColumnType("integer");

                    b.HasKey("GamingPlatformsConsoleId", "VideogameListGameId");

                    b.HasIndex("VideogameListGameId");

                    b.ToTable("VideogamesConsoles", (string)null);
                });

            modelBuilder.Entity("GenreVideogame", b =>
                {
                    b.Property<int>("GenresGenreId")
                        .HasColumnType("integer");

                    b.Property<int>("VideogameListGameId")
                        .HasColumnType("integer");

                    b.HasKey("GenresGenreId", "VideogameListGameId");

                    b.HasIndex("VideogameListGameId");

                    b.ToTable("VideogamesGenres", (string)null);
                });

            modelBuilder.Entity("PublisherVideogame", b =>
                {
                    b.Property<int>("GameListGameId")
                        .HasColumnType("integer");

                    b.Property<int>("PublishersCompanyId")
                        .HasColumnType("integer");

                    b.HasKey("GameListGameId", "PublishersCompanyId");

                    b.HasIndex("PublishersCompanyId");

                    b.ToTable("VideogamesPublishers", (string)null);
                });

            modelBuilder.Entity("TagVideogame", b =>
                {
                    b.Property<int>("TagsTagId")
                        .HasColumnType("integer");

                    b.Property<int>("VideogameListGameId")
                        .HasColumnType("integer");

                    b.HasKey("TagsTagId", "VideogameListGameId");

                    b.HasIndex("VideogameListGameId");

                    b.ToTable("VideogamesTags", (string)null);
                });

            modelBuilder.Entity("UserVideogame", b =>
                {
                    b.Property<string>("UsersUserId")
                        .HasColumnType("text");

                    b.Property<int>("VideogamesGameId")
                        .HasColumnType("integer");

                    b.HasKey("UsersUserId", "VideogamesGameId");

                    b.HasIndex("VideogamesGameId");

                    b.ToTable("UserVideogame");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.CompanyModels.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"CompanySequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("CompanyId"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CompanyId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.CustomFolder", b =>
                {
                    b.Property<int>("FolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FolderId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FolderId");

                    b.ToTable("CustomFolders");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.GamingPlatform", b =>
                {
                    b.Property<int>("ConsoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConsoleId"));

                    b.Property<string>("ConsoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PublisherCompanyId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.HasKey("ConsoleId");

                    b.HasIndex("PublisherCompanyId");

                    b.ToTable("GamingPlatforms");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("ReviewContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReviewTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VideogameUserId")
                        .HasColumnType("integer");

                    b.Property<double>("Vote")
                        .HasColumnType("double precision");

                    b.HasKey("ReviewId");

                    b.HasIndex("VideogameUserId")
                        .IsUnique();

                    b.ToTable("Review");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.VideogameModels.GameMode", b =>
                {
                    b.Property<int>("GameModeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GameModeId"));

                    b.Property<string>("GameModeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GameModeId");

                    b.ToTable("GameModes");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.VideogameModels.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GenreId"));

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.VideogameModels.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagId"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TagId");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.VideogameModels.Videogame", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GameId"));

                    b.Property<int?>("DLCOfWhatGameId")
                        .HasColumnType("integer");

                    b.Property<bool>("EarlyAccess")
                        .HasColumnType("boolean");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<int>("MinPlayers")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.HasKey("GameId");

                    b.HasIndex("DLCOfWhatGameId");

                    b.ToTable("Videogames");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.VideogameModels.VideogameUser", b =>
                {
                    b.Property<int>("VideogameUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VideogameUserId"));

                    b.Property<int>("AchievementsObtained")
                        .HasColumnType("integer");

                    b.Property<int>("AchievementsTotal")
                        .HasColumnType("integer");

                    b.Property<bool>("BetaTested")
                        .HasColumnType("boolean");

                    b.Property<int>("FromVideogameCollectionId")
                        .HasColumnType("integer");

                    b.Property<int>("GameFormat")
                        .HasColumnType("integer");

                    b.Property<int>("GameOwnership")
                        .HasColumnType("integer");

                    b.Property<int>("GamePriority")
                        .HasColumnType("integer");

                    b.Property<int>("GameRegion")
                        .HasColumnType("integer");

                    b.Property<int>("GameStatus")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("HoursPlayed")
                        .HasColumnType("interval");

                    b.Property<bool>("Infinite")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("SubscriptionService")
                        .HasColumnType("integer");

                    b.Property<int>("TimesCompleted")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VideogameId")
                        .HasColumnType("integer");

                    b.HasKey("VideogameUserId");

                    b.HasIndex("FromVideogameCollectionId");

                    b.HasIndex("VideogameId");

                    b.HasIndex("UserId", "VideogameId");

                    b.ToTable("VideogameUsers");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.CompanyModels.Developer", b =>
                {
                    b.HasBaseType("VideogameArchiveAPI.Models.CompanyModels.Company");

                    b.ToTable("Developers");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.CompanyModels.Publisher", b =>
                {
                    b.HasBaseType("VideogameArchiveAPI.Models.CompanyModels.Company");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("CustomFolderVideogameUser", b =>
                {
                    b.HasOne("VideogameArchiveAPI.Models.CustomFolder", null)
                        .WithMany()
                        .HasForeignKey("CustomFoldersFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideogameArchiveAPI.Models.VideogameModels.VideogameUser", null)
                        .WithMany()
                        .HasForeignKey("VideogamesUserVideogameUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeveloperVideogame", b =>
                {
                    b.HasOne("VideogameArchiveAPI.Models.CompanyModels.Developer", null)
                        .WithMany()
                        .HasForeignKey("DevelopersCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideogameArchiveAPI.Models.VideogameModels.Videogame", null)
                        .WithMany()
                        .HasForeignKey("GameListGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameModeVideogame", b =>
                {
                    b.HasOne("VideogameArchiveAPI.Models.VideogameModels.GameMode", null)
                        .WithMany()
                        .HasForeignKey("GameModesGameModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideogameArchiveAPI.Models.VideogameModels.Videogame", null)
                        .WithMany()
                        .HasForeignKey("VideogameListGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamingPlatformVideogame", b =>
                {
                    b.HasOne("VideogameArchiveAPI.Models.GamingPlatform", null)
                        .WithMany()
                        .HasForeignKey("GamingPlatformsConsoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideogameArchiveAPI.Models.VideogameModels.Videogame", null)
                        .WithMany()
                        .HasForeignKey("VideogameListGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenreVideogame", b =>
                {
                    b.HasOne("VideogameArchiveAPI.Models.VideogameModels.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresGenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideogameArchiveAPI.Models.VideogameModels.Videogame", null)
                        .WithMany()
                        .HasForeignKey("VideogameListGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PublisherVideogame", b =>
                {
                    b.HasOne("VideogameArchiveAPI.Models.VideogameModels.Videogame", null)
                        .WithMany()
                        .HasForeignKey("GameListGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideogameArchiveAPI.Models.CompanyModels.Publisher", null)
                        .WithMany()
                        .HasForeignKey("PublishersCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TagVideogame", b =>
                {
                    b.HasOne("VideogameArchiveAPI.Models.VideogameModels.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideogameArchiveAPI.Models.VideogameModels.Videogame", null)
                        .WithMany()
                        .HasForeignKey("VideogameListGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserVideogame", b =>
                {
                    b.HasOne("VideogameArchiveAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideogameArchiveAPI.Models.VideogameModels.Videogame", null)
                        .WithMany()
                        .HasForeignKey("VideogamesGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.GamingPlatform", b =>
                {
                    b.HasOne("VideogameArchiveAPI.Models.CompanyModels.Publisher", "Publisher")
                        .WithMany("GamingConsolesList")
                        .HasForeignKey("PublisherCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.Review", b =>
                {
                    b.HasOne("VideogameArchiveAPI.Models.VideogameModels.VideogameUser", "VideogameUser")
                        .WithOne("Review")
                        .HasForeignKey("VideogameArchiveAPI.Models.Review", "VideogameUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VideogameUser");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.VideogameModels.Videogame", b =>
                {
                    b.HasOne("VideogameArchiveAPI.Models.VideogameModels.Videogame", "DLCOfWhatGame")
                        .WithMany("DLCs")
                        .HasForeignKey("DLCOfWhatGameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DLCOfWhatGame");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.VideogameModels.VideogameUser", b =>
                {
                    b.HasOne("VideogameArchiveAPI.Models.VideogameModels.Videogame", "FromVideogameCollection")
                        .WithMany()
                        .HasForeignKey("FromVideogameCollectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VideogameArchiveAPI.Models.User", "User")
                        .WithMany("VideogamesUser")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideogameArchiveAPI.Models.VideogameModels.Videogame", "Videogame")
                        .WithMany("VideogameUsers")
                        .HasForeignKey("VideogameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromVideogameCollection");

                    b.Navigation("User");

                    b.Navigation("Videogame");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.User", b =>
                {
                    b.Navigation("VideogamesUser");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.VideogameModels.Videogame", b =>
                {
                    b.Navigation("DLCs");

                    b.Navigation("VideogameUsers");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.VideogameModels.VideogameUser", b =>
                {
                    b.Navigation("Review");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.CompanyModels.Publisher", b =>
                {
                    b.Navigation("GamingConsolesList");
                });
#pragma warning restore 612, 618
        }
    }
}
