// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VideogameArchiveAPI.Data;

#nullable disable

namespace VideogameArchiveAPI.Migrations
{
    [DbContext(typeof(VideogameArchiveAPIDbContext))]
    [Migration("20260218124543_RemoveCompanyAndModifyCollectionsTypes")]
    partial class RemoveCompanyAndModifyCollectionsTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CustomFolderVideogameCopy", b =>
                {
                    b.Property<int>("CustomFoldersFolderId")
                        .HasColumnType("integer");

                    b.Property<int>("VideogameCopiesVideogameCopyId")
                        .HasColumnType("integer");

                    b.HasKey("CustomFoldersFolderId", "VideogameCopiesVideogameCopyId");

                    b.HasIndex("VideogameCopiesVideogameCopyId");

                    b.ToTable("CustomFolders_VideogameCopies", (string)null);
                });

            modelBuilder.Entity("CustomFolderVideogameUser", b =>
                {
                    b.Property<int>("CustomFoldersFolderId")
                        .HasColumnType("integer");

                    b.Property<int>("VideogamesUserVideogameUserId")
                        .HasColumnType("integer");

                    b.HasKey("CustomFoldersFolderId", "VideogamesUserVideogameUserId");

                    b.HasIndex("VideogamesUserVideogameUserId");

                    b.ToTable("CustomFolders_VideogameUsers", (string)null);
                });

            modelBuilder.Entity("DeveloperVideogame", b =>
                {
                    b.Property<int>("DevelopersDeveloperId")
                        .HasColumnType("integer");

                    b.Property<int>("GameListGameId")
                        .HasColumnType("integer");

                    b.HasKey("DevelopersDeveloperId", "GameListGameId");

                    b.HasIndex("GameListGameId");

                    b.ToTable("Videogames_Developers", (string)null);
                });

            modelBuilder.Entity("GameModeVideogame", b =>
                {
                    b.Property<int>("GameModesGameModeId")
                        .HasColumnType("integer");

                    b.Property<int>("VideogameListGameId")
                        .HasColumnType("integer");

                    b.HasKey("GameModesGameModeId", "VideogameListGameId");

                    b.HasIndex("VideogameListGameId");

                    b.ToTable("Videogames_GameModes", (string)null);
                });

            modelBuilder.Entity("GamingPlatformVideogame", b =>
                {
                    b.Property<int>("GamingPlatformsPlatformId")
                        .HasColumnType("integer");

                    b.Property<int>("VideogameListGameId")
                        .HasColumnType("integer");

                    b.HasKey("GamingPlatformsPlatformId", "VideogameListGameId");

                    b.HasIndex("VideogameListGameId");

                    b.ToTable("Videogames_GamingPlatforms", (string)null);
                });

            modelBuilder.Entity("GenreVideogame", b =>
                {
                    b.Property<int>("GenresGenreId")
                        .HasColumnType("integer");

                    b.Property<int>("VideogameListGameId")
                        .HasColumnType("integer");

                    b.HasKey("GenresGenreId", "VideogameListGameId");

                    b.HasIndex("VideogameListGameId");

                    b.ToTable("Videogames_Genres", (string)null);
                });

            modelBuilder.Entity("PublisherVideogame", b =>
                {
                    b.Property<int>("GameListGameId")
                        .HasColumnType("integer");

                    b.Property<int>("PublishersPublisherId")
                        .HasColumnType("integer");

                    b.HasKey("GameListGameId", "PublishersPublisherId");

                    b.HasIndex("PublishersPublisherId");

                    b.ToTable("Videogames_Publishers", (string)null);
                });

            modelBuilder.Entity("RealOwnerVideogameCopy", b =>
                {
                    b.Property<int>("RealOwnersRealOwnerId")
                        .HasColumnType("integer");

                    b.Property<int>("VideogameCopiesVideogameCopyId")
                        .HasColumnType("integer");

                    b.HasKey("RealOwnersRealOwnerId", "VideogameCopiesVideogameCopyId");

                    b.HasIndex("VideogameCopiesVideogameCopyId");

                    b.ToTable("VideogameCopy_RealOwner", (string)null);
                });

            modelBuilder.Entity("SubscriptionServiceVideogame", b =>
                {
                    b.Property<int>("SubscriptionServicesSubscriptionServiceId")
                        .HasColumnType("integer");

                    b.Property<int>("VideogamesGameId")
                        .HasColumnType("integer");

                    b.HasKey("SubscriptionServicesSubscriptionServiceId", "VideogamesGameId");

                    b.HasIndex("VideogamesGameId");

                    b.ToTable("SubscriptionServices_Videogames", (string)null);
                });

            modelBuilder.Entity("TagVideogame", b =>
                {
                    b.Property<int>("TagsTagId")
                        .HasColumnType("integer");

                    b.Property<int>("VideogameListGameId")
                        .HasColumnType("integer");

                    b.HasKey("TagsTagId", "VideogameListGameId");

                    b.HasIndex("VideogameListGameId");

                    b.ToTable("Videogames_Tags", (string)null);
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.Entities.CompanyEntities.Developer", b =>
                {
                    b.Property<int>("DeveloperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeveloperId"));

                    b.Property<string>("DeveloperName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DeveloperId");

                    b.ToTable("Developers");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.Entities.CompanyEntities.Publisher", b =>
                {
                    b.Property<int>("PublisherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PublisherId"));

                    b.Property<string>("PublisherName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PublisherId");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.Entities.CustomFolder", b =>
                {
                    b.Property<int>("FolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FolderId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FolderId");

                    b.HasIndex("FolderName");

                    b.ToTable("CustomFolders");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.Entities.GamingPlatform", b =>
                {
                    b.Property<int>("PlatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlatformId"));

                    b.Property<string>("PlatformName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ReleaseDate")
                        .IsRequired()
                        .HasColumnType("date");

                    b.HasKey("PlatformId");

                    b.HasIndex("PublisherId");

                    b.ToTable("GamingPlatforms");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.Entities.RealOwner", b =>
                {
                    b.Property<int>("RealOwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RealOwnerId"));

                    b.Property<string>("RealOwnerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RealOwnerId");

                    b.HasIndex("UserId");

                    b.ToTable("RealOwners");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.Entities.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("ReviewContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReviewTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VideogameUserId")
                        .HasColumnType("integer");

                    b.Property<double?>("Vote")
                        .HasColumnType("double precision");

                    b.HasKey("ReviewId");

                    b.HasIndex("VideogameUserId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.Entities.SubscriptionService", b =>
                {
                    b.Property<int>("SubscriptionServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubscriptionServiceId"));

                    b.Property<double?>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("SubscriptionServiceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SubscriptionServiceId");

                    b.ToTable("SubscriptionServices");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.Entities.VideogameEntities.GameMode", b =>
                {
                    b.Property<int>("GameModeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GameModeId"));

                    b.Property<string>("GameModeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GameModeId");

                    b.ToTable("GameModes");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.Entities.VideogameEntities.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GenreId"));

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.Entities.VideogameEntities.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagId"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.Entities.VideogameEntities.Videogame", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GameId"));

                    b.Property<int?>("DLCOfWhatGameId")
                        .HasColumnType("integer");

                    b.Property<bool>("EarlyAccess")
                        .HasColumnType("boolean");

                    b.Property<int?>("FromVideogameCollectionId")
                        .HasColumnType("integer");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<int>("MinPlayers")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.HasKey("GameId");

                    b.HasIndex("DLCOfWhatGameId");

                    b.HasIndex("FromVideogameCollectionId");

                    b.HasIndex("GameName");

                    b.ToTable("Videogames");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.Entities.VideogameEntities.VideogameCopy", b =>
                {
                    b.Property<int>("VideogameCopyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VideogameCopyId"));

                    b.Property<int>("AchievementsObtained")
                        .HasColumnType("integer");

                    b.Property<int>("AchievementsTotal")
                        .HasColumnType("integer");

                    b.Property<int>("FromVideogameCollectionId")
                        .HasColumnType("integer");

                    b.Property<int>("GameFormat")
                        .HasColumnType("integer");

                    b.Property<int>("GameOwnership")
                        .HasColumnType("integer");

                    b.Property<int>("GamePriority")
                        .HasColumnType("integer");

                    b.Property<int>("GameRegion")
                        .HasColumnType("integer");

                    b.Property<int>("GameStatus")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("HoursPlayed")
                        .HasColumnType("interval");

                    b.Property<DateOnly?>("PlayedFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("PlayedTo")
                        .HasColumnType("date");

                    b.Property<int>("SubscriptionServiceId")
                        .HasColumnType("integer");

                    b.Property<int>("VideogameUserId")
                        .HasColumnType("integer");

                    b.HasKey("VideogameCopyId");

                    b.HasIndex("FromVideogameCollectionId");

                    b.HasIndex("SubscriptionServiceId");

                    b.HasIndex("VideogameUserId");

                    b.ToTable("VideogameCopies");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.Entities.VideogameEntities.VideogameUser", b =>
                {
                    b.Property<int>("VideogameUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VideogameUserId"));

                    b.Property<bool>("BetaTested")
                        .HasColumnType("boolean");

                    b.Property<bool>("Infinite")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("TimesCompleted")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VideogameId")
                        .HasColumnType("integer");

                    b.HasKey("VideogameUserId");

                    b.HasIndex("VideogameId");

                    b.HasIndex("UserId", "VideogameId")
                        .IsUnique();

                    b.ToTable("VideogameUsers");
                });

            modelBuilder.Entity("CustomFolderVideogameCopy", b =>
                {
                    b.HasOne("VideogameArchiveAPI.Models.Entities.CustomFolder", null)
                        .WithMany()
                        .HasForeignKey("CustomFoldersFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideogameArchiveAPI.Models.Entities.VideogameEntities.VideogameCopy", null)
                        .WithMany()
                        .HasForeignKey("VideogameCopiesVideogameCopyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CustomFolderVideogameUser", b =>
                {
                    b.HasOne("VideogameArchiveAPI.Models.Entities.CustomFolder", null)
                        .WithMany()
                        .HasForeignKey("CustomFoldersFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideogameArchiveAPI.Models.Entities.VideogameEntities.VideogameUser", null)
                        .WithMany()
                        .HasForeignKey("VideogamesUserVideogameUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeveloperVideogame", b =>
                {
                    b.HasOne("VideogameArchiveAPI.Models.Entities.CompanyEntities.Developer", null)
                        .WithMany()
                        .HasForeignKey("DevelopersDeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideogameArchiveAPI.Models.Entities.VideogameEntities.Videogame", null)
                        .WithMany()
                        .HasForeignKey("GameListGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameModeVideogame", b =>
                {
                    b.HasOne("VideogameArchiveAPI.Models.Entities.VideogameEntities.GameMode", null)
                        .WithMany()
                        .HasForeignKey("GameModesGameModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideogameArchiveAPI.Models.Entities.VideogameEntities.Videogame", null)
                        .WithMany()
                        .HasForeignKey("VideogameListGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamingPlatformVideogame", b =>
                {
                    b.HasOne("VideogameArchiveAPI.Models.Entities.GamingPlatform", null)
                        .WithMany()
                        .HasForeignKey("GamingPlatformsPlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideogameArchiveAPI.Models.Entities.VideogameEntities.Videogame", null)
                        .WithMany()
                        .HasForeignKey("VideogameListGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenreVideogame", b =>
                {
                    b.HasOne("VideogameArchiveAPI.Models.Entities.VideogameEntities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresGenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideogameArchiveAPI.Models.Entities.VideogameEntities.Videogame", null)
                        .WithMany()
                        .HasForeignKey("VideogameListGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PublisherVideogame", b =>
                {
                    b.HasOne("VideogameArchiveAPI.Models.Entities.VideogameEntities.Videogame", null)
                        .WithMany()
                        .HasForeignKey("GameListGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideogameArchiveAPI.Models.Entities.CompanyEntities.Publisher", null)
                        .WithMany()
                        .HasForeignKey("PublishersPublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealOwnerVideogameCopy", b =>
                {
                    b.HasOne("VideogameArchiveAPI.Models.Entities.RealOwner", null)
                        .WithMany()
                        .HasForeignKey("RealOwnersRealOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideogameArchiveAPI.Models.Entities.VideogameEntities.VideogameCopy", null)
                        .WithMany()
                        .HasForeignKey("VideogameCopiesVideogameCopyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SubscriptionServiceVideogame", b =>
                {
                    b.HasOne("VideogameArchiveAPI.Models.Entities.SubscriptionService", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionServicesSubscriptionServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideogameArchiveAPI.Models.Entities.VideogameEntities.Videogame", null)
                        .WithMany()
                        .HasForeignKey("VideogamesGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TagVideogame", b =>
                {
                    b.HasOne("VideogameArchiveAPI.Models.Entities.VideogameEntities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideogameArchiveAPI.Models.Entities.VideogameEntities.Videogame", null)
                        .WithMany()
                        .HasForeignKey("VideogameListGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.Entities.GamingPlatform", b =>
                {
                    b.HasOne("VideogameArchiveAPI.Models.Entities.CompanyEntities.Publisher", "Publisher")
                        .WithMany("GamingConsolesList")
                        .HasForeignKey("PublisherId");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.Entities.RealOwner", b =>
                {
                    b.HasOne("VideogameArchiveAPI.Models.Entities.User", null)
                        .WithMany("RealOwners")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.Entities.Review", b =>
                {
                    b.HasOne("VideogameArchiveAPI.Models.Entities.VideogameEntities.VideogameUser", "VideogameUser")
                        .WithOne("Review")
                        .HasForeignKey("VideogameArchiveAPI.Models.Entities.Review", "VideogameUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VideogameUser");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.Entities.VideogameEntities.Videogame", b =>
                {
                    b.HasOne("VideogameArchiveAPI.Models.Entities.VideogameEntities.Videogame", "DLCOfWhatGame")
                        .WithMany("DLCs")
                        .HasForeignKey("DLCOfWhatGameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VideogameArchiveAPI.Models.Entities.VideogameEntities.Videogame", "FromVideogameCollection")
                        .WithMany("CollectionOfWhatGames")
                        .HasForeignKey("FromVideogameCollectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DLCOfWhatGame");

                    b.Navigation("FromVideogameCollection");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.Entities.VideogameEntities.VideogameCopy", b =>
                {
                    b.HasOne("VideogameArchiveAPI.Models.Entities.VideogameEntities.Videogame", "FromVideogameCollection")
                        .WithMany()
                        .HasForeignKey("FromVideogameCollectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VideogameArchiveAPI.Models.Entities.SubscriptionService", "SubscriptionService")
                        .WithMany()
                        .HasForeignKey("SubscriptionServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideogameArchiveAPI.Models.Entities.VideogameEntities.VideogameUser", null)
                        .WithMany("VideogameCopies")
                        .HasForeignKey("VideogameUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromVideogameCollection");

                    b.Navigation("SubscriptionService");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.Entities.VideogameEntities.VideogameUser", b =>
                {
                    b.HasOne("VideogameArchiveAPI.Models.Entities.User", "User")
                        .WithMany("VideogamesUser")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideogameArchiveAPI.Models.Entities.VideogameEntities.Videogame", "Videogame")
                        .WithMany("VideogameUsers")
                        .HasForeignKey("VideogameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Videogame");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.Entities.CompanyEntities.Publisher", b =>
                {
                    b.Navigation("GamingConsolesList");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.Entities.User", b =>
                {
                    b.Navigation("RealOwners");

                    b.Navigation("VideogamesUser");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.Entities.VideogameEntities.Videogame", b =>
                {
                    b.Navigation("CollectionOfWhatGames");

                    b.Navigation("DLCs");

                    b.Navigation("VideogameUsers");
                });

            modelBuilder.Entity("VideogameArchiveAPI.Models.Entities.VideogameEntities.VideogameUser", b =>
                {
                    b.Navigation("Review");

                    b.Navigation("VideogameCopies");
                });
#pragma warning restore 612, 618
        }
    }
}
